ktor:
  deployment:
    port: 8080
  application:
    modules:
      - me.orange.SerializationKt.configureSerialization
      - me.orange.WebsocketsKt.configureWebsockets
      - me.orange.RoutingKt.configureRouting

