name: Create Release

on:
  push:
    tags:
      - 'v*' # Triggers on tags like v1.0.0, v1.0.1, etc.

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build and Release Artifacts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Extract project metadata
        run: |
          PROJECT_VERSION=$(grep '^project_version=' gradle.properties | cut -d'=' -f2 | tr -d '\r')
          MINECRAFT_VERSION=$(grep '^minecraft_version=' mod/gradle.properties | cut -d'=' -f2 | tr -d '\r')
          echo "PROJECT_VERSION=$PROJECT_VERSION" >> $GITHUB_ENV
          echo "MINECRAFT_VERSION=$MINECRAFT_VERSION" >> $GITHUB_ENV

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: webapp/package-lock.json

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: "[${{ env.MINECRAFT_VERSION }}] ${{ github.ref_name }}"
          body: |
            ### Requirements & Compatibility
            * **Minecraft Version:** ${{ env.MINECRAFT_VERSION }}
            * **Mod Loader:** NeoForge
            * **Java Version:** 21
          files: |
            backend/build/libs/backend-*.jar
            !backend/build/libs/backend-*-plain.jar
            mod/build/libs/crtangarine-mc*.jar
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
